# Configuration for Alacritty, the GPU enhanced terminal emulator

# Any items in the `env` entry below will be added as
# environment variables. Some entries may override variables
# set by alacritty it self.
env:
  TERM: xterm-256color

# Window dimensions in character columns and lines
# (changes require restart)
window:
  # Window dimensions in character columns and lines
  # Falls back to size specified by window manager if set to 0x0.
  # (changes require restart)
  dimensions:
    columns: 140
    lines: 40

  # Adds this many blank pixels of padding around the window
  # Units are physical pixels; this is not DPI aware.
  # (change requires restart)
  padding:
    x: 2
    y: 2

  # Window decorations
  # Setting this to false will result in window without borders and title bar.
  decorations: full

scrolling:
  history: 10000
  auto_scroll: false

dynamic_title: false

# The FreeType rasterizer needs to know the device DPI for best results
# (changes require restart)
dpi:
  x: 96.0
  y: 96.0

# Display tabs using this many cells (changes require restart)
tabspaces: 8

# When true, bold text is drawn using the bright variant of colors.
draw_bold_text_with_bright_colors: true

# Font configuration (changes require restart)
font:
  normal:
    family: "MesloLGS NF" # should be "Menlo" or something on macOS.
    style: Regular

  bold:
    family: "MesloLGS NF" # should be "Menlo" or something on macOS.
    style: Bold

  italic:
    family: "MesloLGS NF" # should be "Menlo" or something on macOS.
    style: Italic

  size: 11.0

  # Offset is the extra space around each character. offset.y can be thought of
  # as modifying the linespacing, and offset.x as modifying the letter spacing.
  offset:
    x: 0
    y: 0

  # Glyph offset determines the locations of the glyphs within their cells with
  # the default being at the bottom. Increase the x offset to move the glyph to
  # the right, increase the y offset to move the glyph upward.
  glyph_offset:
    x: 0
    y: 0
  # OS X only: use thin stroke font rendering. Thin strokes are suitable
  # for retina displays, but for non-retina you probably want this set to
  # false.
  #use_thin_strokes: true
#Alacritty Themes
colors:
  name: Sweet Love
  author: Boroshlawa
  primary:
    background: "#1F1F1F"
    foreground: "#C0B18B"
  cursor:
    text: "#1F1F1F"
    cursor: "#C0B18B"
  normal:
    black: "#4A3637"
    red: "#D17B49"
    green: "#7B8748"
    yellow: "#AF865A"
    blue: "#535C5C"
    magenta: "#775759"
    cyan: "#6D715E"
    white: "#C0B18B"
  bright:
    black: "#402E2E"
    red: "#AC5D2F"
    green: "#647035"
    yellow: "#8F6840"
    blue: "#444B4B"
    magenta: "#614445"
    cyan: "#585C49"
    white: "#978965"
# Visual Bell
#
# Any time the BEL code is received, Alacritty "rings" the visual bell. Once
# rung, the terminal background will be set to white and transition back to the
# default background color. You can control the rate of this transition by
# setting the `duration` property (represented in milliseconds). You can also
# configure the transition function by setting the `animation` property.
#
# Possible values for `animation`
# `Ease`
# `EaseOut`
# `EaseOutSine`
# `EaseOutQuad`
# `EaseOutCubic`
# `EaseOutQuart`
# `EaseOutQuint`
# `EaseOutExpo`
# `EaseOutCirc`
# `Linear`
#
# To completely disable the visual bell, set its duration to 0.
#
visual_bell:
  animation: EaseOutExpo
  duration: 0

# Background opacity
background.opacity: 1.0
theme: Sweetlove

# Key bindings
#
# Each binding is defined as an object with some properties. Most of the
# properties are optional. All of the alphabetical keys should have a letter for
# the `key` value such as `V`. Function keys are probably what you would expect
# as well (F1, F2, ..). The number keys above the main keyboard are encoded as
# `Key1`, `Key2`, etc. Keys on the number pad are encoded `Number1`, `Number2`,
# etc.  These all match the glutin::VirtualKeyCode variants.
#
# Possible values for `mods`
# `Command`, `Super` refer to the super/command/windows key
# `Control` for the con
